# Generated by Django 4.2.2 on 2023-06-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('diploma', models.FileField(upload_to='diplomas')),
                ('picture', models.FileField(upload_to='pictures')),
                ('phone', models.CharField(max_length=200)),
                ('pasport_seria', models.CharField(max_length=3)),
                ('pasport_raqam', models.IntegerField()),
                ('university', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
