# Generated by Django 4.2.2 on 2023-09-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('consulting', models.CharField(default='', max_length=2500)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('diploma', models.FileField(blank=True, null=True, upload_to='diplomas/')),
                ('picture', models.FileField(blank=True, null=True, upload_to='pictures/')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('pasport_seria', models.CharField(blank=True, max_length=3)),
                ('pasport_raqam', models.IntegerField(blank=True, null=True)),
                ('is_student', models.BooleanField(default=False)),
                ('university', models.CharField(blank=True, default='', max_length=200)),
                ('faculty', models.CharField(blank=True, default='', max_length=200)),
                ('study_time', models.CharField(blank=True, default='', max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=2500)),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=25000)),
                ('ID_raqam', models.CharField(max_length=2500)),
                ('director', models.CharField(max_length=2500)),
                ('place_office', models.CharField(max_length=25000000)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500)),
                ('faculty', models.CharField(max_length=250)),
                ('ID_raqam', models.CharField(max_length=2500)),
                ('place', models.CharField(max_length=2500)),
                ('time_study', models.CharField(choices=[('kunduzgi', 'kunduzgi'), ('sirtqi', 'sirtqi'), ('kechki', 'kechki')], max_length=250)),
                ('bio', models.CharField(max_length=50000)),
                ('date_begin', models.DateField()),
                ('mission', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_raqam', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('is_univer', models.BooleanField(default=False)),
            ],
        ),
    ]
