# Generated by Django 4.2.2 on 2023-06-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
