# Generated by Django 4.2.2 on 2023-06-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_clients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='diploma',
            field=models.FileField(blank=True, upload_to='diplomas'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='picture',
            field=models.FileField(blank=True, upload_to='pictures'),
        ),
    ]
