# Generated by Django 4.2.2 on 2023-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_clients_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='faculty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clients',
            name='pasport_raqam',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='pasport_seria',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clients',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
