# Generated by Django 4.2.2 on 2023-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_clients_faculty_alter_clients_pasport_raqam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='pasport_raqam',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
