# Generated by Django 4.2.2 on 2023-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_clients_pasport_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
