# Generated by Django 4.2.2 on 2023-06-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_clients_email_alter_clients_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_univer',
            field=models.BooleanField(default=False),
        ),
    ]
