# Generated by Django 4.2.2 on 2023-06-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_clients_certificates_user_is_univer'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500)),
                ('faculty', models.CharField(max_length=250)),
                ('time_study', models.CharField(choices=[('kunduzgi', 'kunduzgi'), ('sirtqi', 'sirtqi'), ('kechki', 'kechki')], max_length=250)),
            ],
        ),
    ]
