# Generated by Django 4.2.2 on 2023-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_clients_study_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=2500)),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=25000)),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='consulting',
            field=models.CharField(default=1, max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='place',
            field=models.CharField(default=1, max_length=2500),
            preserve_default=False,
        ),
    ]
