# Generated by Django 4.2.2 on 2023-07-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20230705_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulting',
            name='ID_raqam',
        ),
    ]
