# Generated by Django 4.2.2 on 2023-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_consulting_id_raqam'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='ID_raqam',
            field=models.CharField(default=1, max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='ID_raqam',
            field=models.CharField(default=1, max_length=2500),
            preserve_default=False,
        ),
    ]
