# Generated by Django 4.2.2 on 2023-07-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_consulting_id_raqam_university_id_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='diploma',
            field=models.FileField(blank=True, upload_to='diplomas/'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='picture',
            field=models.FileField(blank=True, upload_to='pictures/'),
        ),
    ]
