# Generated by Django 4.2.2 on 2023-07-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_clients_certificates_alter_clients_diploma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='consulting',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='clients',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clients',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='study_time',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='clients',
            name='university',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
